spring.application.name=api-gateway

spring.cloud.config.uri=${CONFIG_SERVER_URL:http://config-service:8000}

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://config-service:8000}

# Charger le .env depuis la racine du projet
dotenv.directory=../
