spring.application.name=client-service
server.port=8081

spring.cloud.config.uri=${CONFIG_SERVER_URL:http://localhost:8000}
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8000}

dotenv.directory=../

# Base de données
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/microfinancehub_client}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Flyway désactivé
spring.flyway.enabled=false

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# Redis (rate limiting)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# JWT
jwt.secret=${JWT_SECRET:}

# Upload documents
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
app.upload.dir=uploads
app.service.base-url=http://localhost:8081

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Cloudinary
cloudinary.url=${CLOUDINARY_URL:}
