spring.application.name=registry-service
server.port=8761
spring.cloud.config.uri=${CONFIG_SERVER_URL:http://config-service:8000}
spring.config.import=optional:configserver:

# Charger le .env depuis la racine du projet
dotenv.directory=../
