spring.application.name=account-service

spring.cloud.config.uri=${CONFIG_SERVER_URL:http://config-service:8000}

spring.config.import=configserver:${CONFIG_SERVER_URL:http://config-service:8000}

# Charger le .env depuis la racine du projet
dotenv.directory=../
