spring.application.name=loan-service
server.port=8083
spring.cloud.config.uri=${CONFIG_SERVER_URL:http://config-service:8000}
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://config-service:8000}
spring.flyway.enabled=false

# Charger le .env depuis la racine du projet
dotenv.directory=../
