spring.application.name=agency-service
server.port=8086
spring.cloud.config.uri=${CONFIG_SERVER_URL:http://config-service:8000}
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://config-service:8000}

dotenv.directory=../
